const { ipcRenderer } = window.require('electron');
import white from '@img/KeyboardIcons/White';

class GlobalShortcut {
    //map js keycodes to electron keycodes
    static reactToElectron = new Map([
        [8, 'Backspace'],
        [9, 'Tab'],
        [13, 'Enter'],
        [16, 'Shift'],
        [17, 'CmdOrCtrl'],
        [18, 'Alt'],
        [19, 'Pause'],
        [20, 'CapsLock'],
        [27, 'Escape'],
        [32, 'Space'],
        [33, 'PageUp'],
        [34, 'PageDown'],
        [35, 'End'],
        [36, 'Home'],
        [37, 'Left'],
        [38, 'Up'],
        [39, 'Right'],
        [40, 'Down'],
        [45, 'Insert'],
        [46, 'Delete'],
        [48, '0'],
        [49, '1'],
        [50, '2'],
        [51, '3'],
        [52, '4'],
        [53, '5'],
        [54, '6'],
        [55, '7'],
        [56, '8'],
        [57, '9'],
        [65, 'A'],
        [66, 'B'],
        [67, 'C'],
        [68, 'D'],
        [69, 'E'],
        [70, 'F'],
        [71, 'G'],
        [72, 'H'],
        [73, 'I'],
        [74, 'J'],
        [75, 'K'],
        [76, 'L'],
        [77, 'M'],
        [78, 'N'],
        [79, 'O'],
        [80, 'P'],
        [81, 'Q'],
        [82, 'R'],
        [83, 'S'],
        [84, 'T'],
        [85, 'U'],
        [86, 'V'],
        [87, 'W'],
        [88, 'X'],
        [89, 'Y'],
        [90, 'Z'],
        [91, 'Meta'],
        [93, 'ContextMenu'],
        [96, 'Numpad0'],
        [97, 'Numpad1'],
        [98, 'Numpad2'],
        [99, 'Numpad3'],
        [100, 'Numpad4'],
        [101, 'Numpad5'],
        [102, 'Numpad6'],
        [103, 'Numpad7'],
        [104, 'Numpad8'],
    ]);

    getIconForKeycode(keycode) {
        
    }
}

export default GlobalShortcut;