name: Build and Release for Windows

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    if: contains(github.event.head_commit.message, 'Create new release')

    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.zth_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for the React frontend
        shell: pwsh
        run: npm install
        working-directory: ./echo

      - name: Install dependencies for the Electron app
        shell: pwsh
        run: npm install
        working-directory: ./electron

      - name: Build Electron App
        id: build_electron_app
        shell: pwsh
        working-directory: ./electron
        run: |
          npm run dist
          dir .\dist

      - name: Extract echo version from package.json
        id: extract_echo_version
        shell: pwsh
        run: |
          $pkg_version = (Get-Content -Path .\echo\package.json | ConvertFrom-Json).version
          echo "Version: $pkg_version"
          echo "release_echo_version=$pkg_version" >> $ENV:GITHUB_OUTPUT
      
      - name: Extract electron version from package.json
        id: extract_electorn_version
        shell: pwsh
        run: |
          $pkg_version = (Get-Content -Path .\electron\package.json | ConvertFrom-Json).version
          echo "Version: $pkg_version"
          echo "release_electron_version=$pkg_version" >> $ENV:GITHUB_OUTPUT

      - name: Check if version is a pre-release
        id: check_pre_release
        shell: pwsh
        run: |
          $version = "${{ steps.extract_echo_version.outputs.release_echo_version }}"
          echo "Version: $version"
          $first_digit = $version.Split('.')[0]
          $override = $true
          if ($override -eq $true) {
            echo "is_prerelease=false" >> $ENV:GITHUB_OUTPUT
          } else {
            if ($first_digit -ne '0') {
              echo "is_prerelease=false" >> $ENV:GITHUB_OUTPUT
            } else {
              echo "is_prerelease=true" >> $ENV:GITHUB_OUTPUT
            }
          }

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_echo_version.outputs.release_echo_version }}
          release_name: Release v${{ steps.extract_echo_version.outputs.release_echo_version }}
          draft: false
          prerelease: ${{ steps.check_pre_release.outputs.is_prerelease }}
          body: |
            This is a new release of the Echo app.
            - This release contains the latest version of the Echo app.
            - This release contains the latest version of the Electron app.

      - name: Upload Executables
        id: upload-executables
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.zth_token }}
          file: ./electron/dist/Echo-Setup-${{ steps.extract_echo_version.outputs.release_echo_version }}.exe
          asset_name: Echo-Setup-${{ steps.extract_echo_version.outputs.release_echo_version }}.exe
          tag: ${{ steps.extract_echo_version.outputs.release_echo_version }}
          overwrite: true
          make_latest: true
      
      - name: Upload blockmap
        id: upload-blockmap
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.zth_token }}
          file: ./electron/dist/Echo-Setup-${{ steps.extract_echo_version.outputs.release_echo_version }}.exe.blockmap
          asset_name: Echo-Setup-${{ steps.extract_echo_version.outputs.release_echo_version }}.exe.blockmap
          tag: ${{ steps.extract_echo_version.outputs.release_echo_version }}
          overwrite: true
          make_latest: true
        
      - name: Upload builder debug
        id: upload-builder-debug
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.zth_token }}
          file: ./electron/dist/builder-debug.yml
          asset_name: builder-debug.yml
          tag: ${{ steps.extract_echo_version.outputs.release_echo_version }}
          overwrite: true
          make_latest: true

      # - name: Upload builder-effective-config
      #   id: upload-builder-effective-config
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.zth_token }}
      #     file: ./electron/dist/builder-effective-config.yaml
      #     asset_name: builder-effective-config.yaml
      #     tag: ${{ steps.extract_echo_version.outputs.release_echo_version }}
      #     overwrite: true
      #     make_latest: true

      - name: Upload latest.yml
        id: upload-latest-yml
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.zth_token }}
          file: ./electron/dist/latest.yml
          asset_name: latest.yml
          tag: ${{ steps.extract_echo_version.outputs.release_echo_version }}
          overwrite: true
          make_latest: true
  update-readme:
    runs-on: ubuntu-latest
    needs: build-and-release-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.zth_token }}
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf-8');
            const newReadme = readme.replace(/v\d+\.\d+\.\d+/g, `v${{ steps.build-and-release-windows.outputs.release_echo_version }}`);
            fs.writeFileSync('README.md', newReadme);
            console.log('README updated');

      - name: Commit changes
        run: |
          git config --global user.name 'Automatic update'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.zth_token }}@github.com/${{ github.repository }}
          git commit -am "Updated version of readme"
          git push
